version: "3.9"

services:
  api:
    build: .
    container_name: picvid-tags-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data:Z
    restart: unless-stopped
    # environment:
    #   - DB_RESET=true

  ui:
    build:
      context: ./ui
    container_name: picvid-tags-ui
    ports:
      - "3000:5173"
    environment:
      - VITE_API_BASE=http://localhost:8000
    depends_on:
      - api